FROM mcr.microsoft.com/playwright:v1.58.0-noble

RUN apt-get update && \
    apt-get install -y openssl && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm@latest

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma/
COPY prisma.config.ts ./
RUN pnpm install

# Generate Prisma client
RUN npx prisma generate

COPY . .

# Install bull-board dependencies
RUN cd bull-board && CI=true pnpm install
