import {
  Globe,
  GitCompareArrows,
  Brain,
  MousePointerClick,
  FileDown,
  ShieldCheck,
} from "lucide-react";

const features = [
  {
    icon: Globe,
    title: "Full-site crawling",
    description:
      "Follows every internal link. Parses sitemaps. Scans pages concurrently with configurable parallelism.",
  },
  {
    icon: GitCompareArrows,
    title: "Issue tracking",
    description:
      "Track new, fixed, and recurring issues across crawls. Dismiss false positives. Measure progress over time.",
  },
  {
    icon: Brain,
    title: "AI fix suggestions",
    description:
      "Every issue gets a human-readable explanation and step-by-step fix — generated by AI, not template text.",
  },
  {
    icon: MousePointerClick,
    title: "Visual inspector",
    description:
      "See the exact element highlighted on a screenshot. Toggle to HTML view. Navigate between occurrences.",
  },
  {
    icon: FileDown,
    title: "PDF & Excel export",
    description:
      "Executive-summary PDF reports. Filterable Excel spreadsheets. Share results with anyone.",
  },
  {
    icon: ShieldCheck,
    title: "WCAG 2.1 A & AA",
    description:
      "50+ axe-core rules plus custom engines for link text and touch targets. Confirmed and potential issues separated.",
  },
];

export function Features() {
  return (
    <section className="border-t border-border/30 bg-muted/30 py-24">
      <div className="mx-auto max-w-6xl px-6">
        <div className="mb-16 flex flex-col items-center text-center">
          <p className="text-[11px] font-bold uppercase tracking-[0.2em] text-[#E90029]">
            Capabilities
          </p>
          <h2 className="mt-3 text-3xl font-extrabold tracking-tight text-foreground sm:text-4xl">
            Everything you need for compliance
          </h2>
          <p className="mt-3 max-w-lg text-[15px] leading-relaxed text-muted-foreground">
            From automated scanning to AI-powered remediation — one tool covers your entire accessibility workflow.
          </p>
        </div>

        <div className="grid gap-px overflow-hidden rounded-2xl border border-border/50 bg-border/50 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature) => {
            const Icon = feature.icon;
            return (
              <div
                key={feature.title}
                className="group bg-card p-7 transition-colors duration-300 hover:bg-card/80"
              >
                <div className="mb-4 flex size-10 items-center justify-center rounded-xl bg-muted/80 transition-colors duration-300 group-hover:bg-[#E90029]/[0.08]">
                  <Icon className="size-[18px] text-muted-foreground transition-colors duration-300 group-hover:text-[#E90029]" />
                </div>
                <h3 className="mb-2 text-[15px] font-bold text-foreground">
                  {feature.title}
                </h3>
                <p className="text-[13px] leading-[1.7] text-muted-foreground">
                  {feature.description}
                </p>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
