import { config } from '@/config'
import type { RawFinding } from '../../scanner/types'
import type {
  AIProvider,
  EnrichedIssue,
  PageContext,
  ScanSummary,
} from '../types'
import { buildEnrichIssuesPrompt } from '../prompts/enrich-issues'
import { buildGenerateSummaryPrompt } from '../prompts/generate-summary'

interface ChatMessage {
  role: 'system' | 'user' | 'assistant'
  content: string
}

interface AzureOpenAIResponse {
  choices: Array<{
    message: {
      content: string
    }
    finish_reason: string
  }>
  usage: {
    prompt_tokens: number
    completion_tokens: number
    total_tokens: number
  }
}

const MAX_RETRIES = 1
const RETRY_DELAY_MS = 1000

export class AzureOpenAIProvider implements AIProvider {
  private endpoint: string
  private apiKey: string

  constructor() {
    this.endpoint = config.ai.endpoint
    this.apiKey = config.ai.apiKey
  }

  async enrichIssues(
    rawFindings: RawFinding[],
    pageContext: PageContext,
  ): Promise<EnrichedIssue[]> {
    if (rawFindings.length === 0) return []

    const { system, user } = buildEnrichIssuesPrompt(rawFindings, pageContext)
    const messages: ChatMessage[] = [
      { role: 'system', content: system },
      { role: 'user', content: user },
    ]

    const responseText = await this.chatCompletion(messages)
    const parsed = JSON.parse(responseText)

    // LLM returns { "issues": [...] } due to json_object mode requiring a top-level object
    const issues = Array.isArray(parsed) ? parsed : parsed.issues
    if (!Array.isArray(issues)) {
      throw new Error(
        `Expected issues array in enrich-issues response, got ${typeof parsed}`,
      )
    }

    // Build a lookup from ruleId to ruleHelp from raw findings
    const ruleHelpByRuleId = new Map<string, string>()
    for (const finding of rawFindings) {
      if (!ruleHelpByRuleId.has(finding.ruleId)) {
        ruleHelpByRuleId.set(finding.ruleId, finding.ruleHelp)
      }
    }

    // Attach ruleHelp from raw findings (not generated by LLM)
    return (issues as EnrichedIssue[]).map((issue) => ({
      ...issue,
      ruleHelp: ruleHelpByRuleId.get(issue.ruleId) ?? '',
    }))
  }

  async generateSummary(
    issues: EnrichedIssue[],
    pageContext: PageContext,
  ): Promise<ScanSummary> {
    const { system, user } = buildGenerateSummaryPrompt(issues, pageContext)
    const messages: ChatMessage[] = [
      { role: 'system', content: system },
      { role: 'user', content: user },
    ]

    const responseText = await this.chatCompletion(messages)
    const parsed = JSON.parse(responseText)

    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
      throw new Error(
        `Expected JSON object from generate-summary response, got ${typeof parsed}`,
      )
    }

    return parsed as ScanSummary
  }

  private async chatCompletion(messages: ChatMessage[]): Promise<string> {
    const url = this.endpoint

    const body = {
      messages,
      temperature: 0.2,
      max_tokens: 16384,
      response_format: { type: 'json_object' as const },
    }

    let lastError: Error | null = null

    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
      try {
        const response = await fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'api-key': this.apiKey,
          },
          body: JSON.stringify(body),
        })

        if (!response.ok) {
          const errorBody = await response.text()
          throw new Error(
            `Azure OpenAI API error (${response.status}): ${errorBody}`,
          )
        }

        const data = (await response.json()) as AzureOpenAIResponse

        const choice = data.choices?.[0]
        if (!choice) {
          throw new Error('Azure OpenAI returned no choices in response')
        }

        if (choice.finish_reason === 'content_filter') {
          throw new Error(
            'Azure OpenAI content filter triggered; response was blocked',
          )
        }

        const content = choice.message?.content
        if (!content) {
          throw new Error('Azure OpenAI returned empty message content')
        }

        return content
      } catch (error) {
        lastError = error instanceof Error ? error : new Error(String(error))

        if (attempt < MAX_RETRIES) {
          await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS))
        }
      }
    }

    throw new Error(
      `Azure OpenAI request failed after ${MAX_RETRIES + 1} attempts: ${lastError?.message}`,
    )
  }
}
